name: "Remove Azure Source List Action"
description: "This Action will remove azure from the source list on ubuntu os."
author: christopherpickering
branding:
  icon: "x-circle"
  color: "orange"
runs:
  using: "composite"
  steps:
    - id: clean-source-list
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
        fi
      shell: bash
